/*
 * race-timing - <https://github.com/grahamkirby/race-timing>
 * Copyright © 2026 Graham Kirby (race-timing@kirby-family.net)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.grahamkirby.race_timing;


import com.code_intelligence.jazzer.api.FuzzedDataProvider;
import com.code_intelligence.jazzer.junit.FuzzTest;
import com.code_intelligence.jazzer.mutation.annotation.NotNull;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.canvas.parser.PdfTextExtractor;
import org.grahamkirby.race_timing.common.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.LogManager;
import java.util.logging.Logger;
import java.util.stream.Stream;

import static java.nio.file.FileVisitResult.CONTINUE;
import static org.grahamkirby.race_timing.common.Config.*;
import static org.junit.jupiter.api.Assertions.*;

@SuppressWarnings("preview")
public class RaceTest {

    //////////////////////////////////////////////////////////////////////////////////////////////////

    // Each test specifies a set of input files, located in test/resources, and checks either that the
    // expected output files are generated, or that the expected error occurs.

    // If the property USER_TEST_DIRECTORY_PATH is undefined in the test config file then output files
    // are generated within a temporary directory and deleted at the end of each test.
    // If the property is defined then output files are generated within the specified directory.

    private static final String KEY_USER_TEST_DIRECTORY_PATH = "USER_TEST_DIRECTORY_PATH";

    // If the flag RETAIN_FIRST_OUTPUT is also enabled, then the output files generated by the first
    // test are retained for inspection at the end of the run. Otherwise, the output files generated by
    // the first failing test, if any, are retained.

    private static final String KEY_RETAIN_FIRST_OUTPUT = "RETAIN_FIRST_OUTPUT";

    private static final Path TEST_RESOURCES_ROOT = Path.of("src", "test", "resources");

    private static final String FUZZ_OUTPUT_PREFIX = "INFO: Instrumented";

    private static final String FILE_NAME_PER_TEST_CONFIG = "config.txt";
    private static final String FILE_NAME_OVERALL_TEST_CONFIG = "test_config.txt";
    private static final String FILE_NAME_ENTRIES = "entries.txt";
    private static final String FILE_NAME_RAW_TIMES = "rawtimes.txt";

    private static final String DIR_NAME_INPUT = "input";
    private static final String DIR_NAME_OUTPUT = "output";
    private static final String DIR_NAME_REAL_RACES = "real";
    private static final String DIR_NAME_SYNTHETIC_RACES = "synthetic";
    private static final String DIR_NAME_EXPECTED_OUTPUT = "expected";
    private static final String DIR_NAME_OUTPUT_RETAINED = "output_retained";
    private static final String DIR_NAME_INDIVIDUAL_RACES = "individual_race";
    private static final String DIR_NAME_SPECIAL_CASES = "special_cases";
    private static final String DIR_NAME_MISSING_CONFIG = "missing_config_file";
    private static final String DIR_NAME_INVALID_RACE_TYPE = "invalid_race_type";

    private static final String ERROR_CANNOT_CREATE_OUTPUT_DIRECTORY = "cannot create output directory, or file within it";
    private static final String ERROR_NO_APPLICABLE_RACE_TYPE = "no applicable race type for config file";
    private static final String ERROR_MISSING_CONFIG = "missing config file";
    private static final String ERROR_EXPECTED_DIRECTORY_MISSING = "expected directory missing";
    private static final String ERROR_UNEXPECTED_DIRECTORY = "unexpected directory";
    private static final String ERROR_DIFFERENCE_IN_FILES = "difference in files";
    private static final String ERROR_READING_EXPECTED_OUTPUT_FILE = "error reading expected output file";
    private static final String ERROR_UNEXPECTED_ERROR_MESSAGE = "unexpected error message";

    private static final int FUZZED_CONTENT_MAX_LENGTH = 1000;

    private final boolean debug;
    private final String user_test_directory_path_string;
    private final boolean retain_first_output;

    // File names that may be present in list of expected output files for a given test, but should be ignored.
    private List<String> ignored_file_names;

    // Whether the current test is the first test in the run.
    private static boolean first_test = true;

    // Whether at least one test failed earlier in the run.
    @SuppressWarnings("BooleanVariableAlwaysNegated")
    private static boolean previous_failed_test = false;

    // Whether the current test failed.
    private boolean failed_test = true;

    //////////////////////////////////////////////////////////////////////////////////////////////////

    private Path reference_input_directory;
    private Path reference_expected_directory;

    private final Path test_run_directory;
    private Path test_run_input_directory;
    private Path test_run_output_directory;
    private Path test_run_output_retained_directory;

    private Path test_run_input_config;

    //////////////////////////////////////////////////////////////////////////////////////////////////

    public RaceTest() throws IOException {

        final Path overall_test_config_path = TEST_RESOURCES_ROOT.resolve(FILE_NAME_OVERALL_TEST_CONFIG);
        final Properties overall_test_properties = loadProperties(overall_test_config_path);

        user_test_directory_path_string = (String) overall_test_properties.get(KEY_USER_TEST_DIRECTORY_PATH);

        debug = user_test_directory_path_string != null;
        test_run_directory = getTempDirectory();
        retain_first_output = Boolean.parseBoolean((String) overall_test_properties.get(KEY_RETAIN_FIRST_OUTPUT));

        setLoggingLevel(debug ? Level.INFO : Level.WARNING);
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////

    @AfterEach
    public void tearDown() throws IOException {

        if (debug) {

            // Whether this is the first test in the run to have failed.
            final boolean first_failed_test = failed_test && !previous_failed_test;

            // Whether the retained output directory is present from a previous run (in which case it should be deleted).
            final boolean output_directory_retained_from_previous_run = first_test && test_run_output_retained_directory != null && Files.exists(test_run_output_retained_directory);

            // Whether the output directory from this run should be retained, either because this is the first test
            // in the run to fail, or this is the first test in the run and RETAIN_FIRST_OUTPUT is set.
            final boolean output_directory_should_be_retained = first_failed_test || (first_test && retain_first_output);

            // Delete the input and output directories but retain the parent test directory, to make it easier to
            // view the contents on repeated debugging runs.
            // Also retain a copy of the output directory for review if appropriate.
            cleanUpDirectories(output_directory_retained_from_previous_run, output_directory_should_be_retained);

            first_test = false;
            if (first_failed_test) previous_failed_test = true;

        } else
            deleteDirectory(test_run_directory);
    }

    private void cleanUpDirectories(final boolean output_directory_retained_from_previous_run, final boolean output_directory_should_be_retained) throws IOException {

        if (output_directory_retained_from_previous_run)
            deleteDirectory(test_run_output_retained_directory);

        if (output_directory_should_be_retained)
            copyDirectory(test_run_output_directory, test_run_output_retained_directory);

        deleteDirectory(test_run_input_directory);
        deleteDirectory(test_run_output_directory);
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////

    @ParameterizedTest
    @MethodSource("getTestCases")
    public void testFromDirectory(final Path test_resource_root) throws Exception {

        configureDirectories(test_resource_root);
        configureDirectoryContents(reference_input_directory);

        final String[] args = {test_run_input_config.toString()};
        final String error_output = processRaceWithDivertedErrorOutput(args);

        // Fuzzing framework may output some unwanted logging to stderr, which should be ignored when checking
        // for an error message.
        assertTrue(error_output.isEmpty() || error_output.startsWith(FUZZ_OUTPUT_PREFIX), ERROR_UNEXPECTED_ERROR_MESSAGE);

        assertThatDirectoryContainsAllExpectedContent(reference_expected_directory, test_run_output_directory);

        // Test has passed if this line is reached.
        failed_test = false;
    }

    @FuzzTest
    @Disabled
    // Disabled since no useful test cases found within reasonable time budget.
    public void fuzzTestFromDirectory(@NotNull final FuzzedDataProvider data) throws Exception {

        reference_input_directory = Files.createTempDirectory(null).resolve(DIR_NAME_INPUT);
        Files.createDirectories(reference_input_directory);

        final Path config_path = reference_input_directory.resolve(FILE_NAME_PER_TEST_CONFIG);
        final Path entries_path = reference_input_directory.resolve(FILE_NAME_ENTRIES);
        final Path rawtimes_path = reference_input_directory.resolve(FILE_NAME_RAW_TIMES);

        test_run_input_directory = test_run_directory.resolve(DIR_NAME_INPUT);
        test_run_output_directory = test_run_directory.resolve(DIR_NAME_OUTPUT);
        test_run_input_config = test_run_input_directory.resolve(FILE_NAME_PER_TEST_CONFIG);

        final String config_file_content = """
            YEAR = 2023
            RACE_NAME_FOR_RESULTS = Balmullo Trail Race
            RACE_NAME_FOR_FILENAMES = balmullo
            ENTRIES_PATH = entries.txt
            RAW_RESULTS_PATH = rawtimes.txt""";

        final String fuzzed_entries_file_content = data.consumeAsciiString(FUZZED_CONTENT_MAX_LENGTH);
        final String fuzzed_rawtimes_file_content = data.consumeAsciiString(FUZZED_CONTENT_MAX_LENGTH);

        Files.writeString(config_path, config_file_content);
        Files.writeString(entries_path, fuzzed_entries_file_content);
        Files.writeString(rawtimes_path, fuzzed_rawtimes_file_content);

        configureDirectoryContents(reference_input_directory);

        RaceFactory.main(new String[]{test_run_input_config.toString()});
    }

    @Test
    @Disabled
    public void missingConfigFile() {

        // This omits the normal setup phase of copying the source and expected files.

        final String error_output;
        final Path missing_config_path = Path.of(DIR_NAME_SYNTHETIC_RACES, DIR_NAME_SPECIAL_CASES, DIR_NAME_MISSING_CONFIG);

        try {
            final ByteArrayOutputStream diverted_err = new ByteArrayOutputStream();
            System.setErr(new PrintStream(diverted_err));

            RaceFactory.main(new String[]{missing_config_path.toString()});

            error_output = diverted_err.toString();

        } finally {
            System.setErr(System.err);
        }

        // Fuzzing framework may output some unwanted logging to stderr, which should be ignored when checking
        // for an error message.
        assertTrue(error_output.contains(ERROR_MISSING_CONFIG + ": '" + missing_config_path + "'"), "Expected error message was not generated");

        // Test has passed if this line is reached.
        failed_test = false;
    }

    @Test
    @Disabled
    public void missingOrUnwritableOutputDirectory() throws Exception {

        // Randomly selected test case.
        final Path config_path = Path.of(DIR_NAME_REAL_RACES, DIR_NAME_INDIVIDUAL_RACES, "balmullo", "2026");

        configureDirectories(config_path);

        ///////////////////////////////////////////////////

        // Lines adapted from configureDirectoryContents() but output directory is not created.
        if (Files.exists(test_run_input_directory)) deleteDirectory(test_run_input_directory);

        final Path resources_input_directory_relative_to_project = getTestResourcesRootPath(reference_input_directory);

        if (!Files.exists(resources_input_directory_relative_to_project))
            throw new RuntimeException(DIR_NAME_MISSING_CONFIG + ": '" + resources_input_directory_relative_to_project.resolve(FILE_NAME_PER_TEST_CONFIG) + "'");

        copyDirectory(resources_input_directory_relative_to_project, test_run_input_directory);

        ///////////////////////////////////////////////////

        final String[] args = {test_run_input_config.toString()};
        final String error_output = processRaceWithDivertedErrorOutput(args);

        // Fuzzing framework may output some unwanted logging to stderr, which should be ignored when checking
        // for an error message.
        assertTrue(error_output.contains(ERROR_CANNOT_CREATE_OUTPUT_DIRECTORY + ": " + test_run_output_directory));

        // Test has passed if this line is reached.
        failed_test = false;
    }

    @Test
    @Disabled
    public void invalidRaceType() {

        // This omits the normal setup phase of copying the source and expected files.

        final String error_output;
        final Path invalid_config_path = TEST_RESOURCES_ROOT.resolve(DIR_NAME_SYNTHETIC_RACES, DIR_NAME_SPECIAL_CASES, DIR_NAME_INVALID_RACE_TYPE, DIR_NAME_INPUT, FILE_NAME_PER_TEST_CONFIG);

        try {
            final ByteArrayOutputStream diverted_err = new ByteArrayOutputStream();
            System.setErr(new PrintStream(diverted_err));

            RaceFactory.main(new String[]{invalid_config_path.toString()});

            error_output = diverted_err.toString();

        } finally {
            System.setErr(System.err);
        }

        // Fuzzing framework may output some unwanted logging to stderr, which should be ignored when checking
        // for an error message.
        assertTrue(error_output.contains(ERROR_NO_APPLICABLE_RACE_TYPE), "Expected error message was not generated");

        // Test has passed if this line is reached.
        failed_test = false;
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////

    private static List<Path> getTestCases() throws IOException {

        return List.of(TEST_RESOURCES_ROOT.resolve("real/individual_race/balmullo/2023"));

//        try (final Stream<Path> paths = Files.walk(TEST_RESOURCES_ROOT)) {
//
//            // Assume it's a directory containing a test case if it contains a sub-directory named 'expected'.
//            return paths.filter(directory_entry -> Files.isDirectory(directory_entry.resolve(DIR_NAME_EXPECTED_OUTPUT))).toList();
//        }
    }

    private static Path getTestResourcesRootPath(final Path individual_test_resource_root) {

        return TEST_RESOURCES_ROOT.resolve(individual_test_resource_root);
    }

    private static void setLoggingLevel(final Level level) {

        final Logger root_logger = LogManager.getLogManager().getLogger("");
        root_logger.setLevel(level);
    }

    private static String processRaceWithDivertedErrorOutput(final String[] args) {

        final String error_output;
        try {
            final ByteArrayOutputStream diverted_err = new ByteArrayOutputStream();
            System.setErr(new PrintStream(diverted_err));
            System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PRWDEO1");

            RaceFactory.main(args);
            System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PRWDEO2");

            error_output = diverted_err.toString();
            System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PRWDEO3");

        } finally {
            System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PRWDEO4");
            System.setErr(System.err);
        }

        System.out.println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PRWDEO5");
        return error_output;
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////

    private Path getTempDirectory() throws IOException {

        if (debug) {
            final Path temp_dir_path = Path.of(user_test_directory_path_string);
            if (!Files.exists(temp_dir_path)) Files.createDirectory(temp_dir_path);

            return temp_dir_path;
        }

        return Files.createTempDirectory(null);
    }

    private void configureDirectories(final Path test_resource_root) throws IOException {

        reference_input_directory = test_resource_root.resolve(DIR_NAME_INPUT);
        reference_expected_directory = test_resource_root.resolve(DIR_NAME_EXPECTED_OUTPUT);

        test_run_input_directory = test_run_directory.resolve(DIR_NAME_INPUT);
        test_run_output_directory = test_run_directory.resolve(DIR_NAME_OUTPUT);
        test_run_output_retained_directory = test_run_directory.resolve(DIR_NAME_OUTPUT_RETAINED);

        test_run_input_config = test_run_input_directory.resolve(FILE_NAME_PER_TEST_CONFIG);
        ignored_file_names = Config.getIgnoredFileNames();
    }

    private void configureDirectoryContents(final Path reference_input_directory) throws IOException {

        if (Files.exists(test_run_input_directory)) deleteDirectory(test_run_input_directory);
        Files.createDirectories(test_run_output_directory);

        if (!Files.exists(reference_input_directory))
            throw new RuntimeException(ERROR_MISSING_CONFIG + ": '" + reference_input_directory + "/" + FILE_NAME_PER_TEST_CONFIG + "'");
//        throw new RuntimeException(ERROR_MISSING_CONFIG + ": '" + reference_input_directory + File.separator + FILE_NAME_PER_TEST_CONFIG + "'");

        copyDirectory(reference_input_directory, test_run_input_directory);
    }

    private void assertThatDirectoryContainsAllExpectedContent(final Path expected, final Path actual) throws IOException {

        for (final Path expected_entry : getDirectoryEntries(expected)) {

            if (!shouldEntryInExpectedDirectoryBeIgnored(expected_entry)) {

                final Path path_expected = expected.resolve(expected_entry);
                final Path path_actual = actual.resolve(expected_entry);

                if (Files.isDirectory(path_expected)) {

                    assertTrue(Files.isDirectory(path_actual), ERROR_EXPECTED_DIRECTORY_MISSING);
                    assertThatDirectoryContainsAllExpectedContent(path_expected, path_actual);

                } else {
                    assertFalse(Files.isDirectory(path_actual), ERROR_UNEXPECTED_DIRECTORY);
                    assertThatFilesHaveSameContent(path_expected, path_actual);
                }
            }
        }
    }

    private static List<Path> getDirectoryEntries(final Path directory) throws IOException {

        try (final Stream<Path> list = Files.list(directory)) {
            return list.map(Path::getFileName).toList();
        }
    }

    private static void assertThatFilesHaveSameContent(final Path path1, final Path path2) {

        final List<String> file_content1 = getFileContent(path1);
        final List<String> file_content2 = getFileContent(path2);

        for (int i = 0; i < Math.min(file_content1.size(), file_content2.size()); i++) {
            assertEquals(file_content1.get(i), file_content2.get(i), LINE_SEPARATOR + ERROR_DIFFERENCE_IN_FILES + ": " + path1 + " and " + path2 + " at line " + (i + 1) + ":" + LINE_SEPARATOR +
                file_content1.get(i) + LINE_SEPARATOR + file_content2.get(i));
        }

        if (file_content1.size() < file_content2.size())
            assertThatLargerFileDoesNotContainFurtherNonBlankContent(path1, path2);
        if (file_content1.size() > file_content2.size())
            assertThatLargerFileDoesNotContainFurtherNonBlankContent(path2, path1);
    }

    private static void assertThatLargerFileDoesNotContainFurtherNonBlankContent(final Path path_smaller_file, final Path path_larger_file) {

        final List<String> content_smaller_file = getFileContent(path_smaller_file);
        final List<String> content_larger_file = getFileContent(path_larger_file);

        int i = content_smaller_file.size();
        while (i < content_larger_file.size() && content_larger_file.get(i).isBlank()) i++;

        if (i < content_larger_file.size())
            fail(LINE_SEPARATOR + "Difference in files: " + path_smaller_file + " and " + path_larger_file + ": at line " + (i + 1) + ":" + LINE_SEPARATOR + content_larger_file.get(i));
    }

    private static List<String> getFileContent(final Path path) {

        try {
            if (path.toString().endsWith(PDF_FILE_SUFFIX)) {
                try (final PdfDocument document = new PdfDocument(new PdfReader(path.toString()))) {

                    final List<String> contents = new ArrayList<>();
                    for (int i = 1; i <= document.getNumberOfPages(); i++)
                        contents.add(PdfTextExtractor.getTextFromPage(document.getPage(i)));

                    return contents;
                }
            } else return readAllLines(path);

        } catch (final IOException e) {
            fail(ERROR_READING_EXPECTED_OUTPUT_FILE + " " + path + ": " + e);
            throw new RuntimeException(e);
        }
    }

    private boolean shouldEntryInExpectedDirectoryBeIgnored(final Path entry) {

        return ignored_file_names.contains(entry.toString());
    }

    private static void copyDirectory(final Path source_directory, final Path destination_directory) throws IOException {

        Files.walkFileTree(source_directory, new SimpleFileVisitor<>() {

            @Override
            public FileVisitResult preVisitDirectory(final Path dir, final BasicFileAttributes attrs) throws IOException {

                Files.copy(dir, destination_directory.resolve(source_directory.relativize(dir)));
                return CONTINUE;
            }

            @Override
            public FileVisitResult visitFile(final Path file, final BasicFileAttributes attrs) throws IOException {

                Files.copy(file, destination_directory.resolve(source_directory.relativize(file)));
                return CONTINUE;
            }
        });
    }

    private static void deleteDirectory(final Path directory) throws IOException {

        if (directory != null && Files.isDirectory(directory))
            Files.walkFileTree(directory, new SimpleFileVisitor<>() {

                @Override
                public FileVisitResult postVisitDirectory(final Path dir, final IOException exc) throws IOException {

                    Files.delete(dir);
                    return CONTINUE;
                }

                @Override
                public FileVisitResult visitFile(final Path file, final BasicFileAttributes attrs) throws IOException {

                    Files.delete(file);
                    return CONTINUE;
                }
            });
    }
}
