name: 'Maven build and test'
description: 'Maven build and test composite action'

inputs:
  upload-dependencies:
    required: false
    description: 'whether to upload dependencies for analysis'
    default: 'false'

runs:
  using: "composite"

  steps:
  - name: Set up JDK 25
    uses: actions/setup-java@v5
    with:
      java-version: '25'
      distribution: 'corretto'
      cache: 'maven'

  - name: Build and test with Maven
    shell: bash
    run: mvn -B verify

  - name: Upload dependencies
    if: inputs.upload-dependencies == 'true'
    uses: advanced-security/maven-dependency-submission-action@v5
