/*
 * race-timing - <https://github.com/grahamkirby/race-timing>
 * Copyright © 2025 Graham Kirby (graham.kirby@st-andrews.ac.uk)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
package org.grahamkirby.race_timing_experimental;


import org.grahamkirby.race_timing.AbstractRaceTest;
import org.grahamkirby.race_timing.relay_race.RelayRace;
import org.grahamkirby.race_timing_experimental.common.Race;
import org.grahamkirby.race_timing_experimental.relay_race.RelayRaceFactory;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;

import static org.grahamkirby.race_timing.individual_race.TimedRaceInput.KEY_ENTRIES_PATH;
import static org.grahamkirby.race_timing.individual_race.TimedRaceInput.KEY_RAW_RESULTS_PATH;
import static org.grahamkirby.race_timing.relay_race.RelayRace.*;

public class RelayRaceTest extends AbstractRaceTest {

    // TODO test duplicate bib number in individual raw results.
    // TODO test missing property in config file.

    // Synthetic names for most tests generated by:
    // https://www.fakenamegenerator.com/gen-random-gd-uk.php

    @Override
    protected void invokeMain(final String[] args) throws Exception {

        try {
            Race relay_race = RelayRaceFactory.makeRelayRace(Path.of(args[0]));
            relay_race.processResults();

        } catch (final Exception e) {
            System.err.println(e.getMessage());
        }
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////

    @Test
    @Disabled
    void simple() throws Exception {
        testExpectedCompletion("relay_race/simple");
    }

    @Test
    @Disabled
    void legs3() throws Exception {
        testExpectedCompletion("relay_race/legs_3");
    }

    @Test
    @Disabled
    void legs5() throws Exception {
        testExpectedCompletion("relay_race/legs_5");
    }

    @Test
    @Disabled
    void topTwoResultsWomen() throws Exception {
        testExpectedCompletion("relay_race/top_two_results_women");
    }

    @Test
    @Disabled
    void deadHeats() throws Exception {
        testExpectedCompletion("relay_race/dead_heats");
    }

    @Test
    @Disabled
    void htmlOutput() throws Exception {
        testExpectedCompletion("relay_race/html_output");
    }

    @Test
    @Disabled
    void startOffset() throws Exception {
        testExpectedCompletion("relay_race/start_offset");
    }

    @Test
    @Disabled
    void interpolatedRawTimes() throws Exception {
        testExpectedCompletion("relay_race/interpolated_raw_times");
    }

    @Test
    @Disabled
    void guessedMissingBibNumbersA() throws Exception {
        testExpectedCompletion("relay_race/guessed_missing_bib_numbers_a");
    }

    @Test
    @Disabled
    void guessedMissingBibNumbersB() throws Exception {
        testExpectedCompletion("relay_race/guessed_missing_bib_numbers_b");
    }

    @Test
    void lastFewResultsNotRecorded() throws Exception {
        testExpectedCompletion("relay_race/last_few_results_not_recorded");
    }

    @Test
    @Disabled
    void massStartNoneDNFLeg1() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_1");
    }

    @Test
    @Disabled
    void massStartNoneDNFLeg1And2And3() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_1_2_3");
    }

    @Test
    @Disabled
    void massStartNoneDNFButCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_1_2_3_4a");
    }

    @Test
    @Disabled
    void massStartNoneDNFNotCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_1_2_3_4b");
    }

    @Test
    @Disabled
    void massStartNoneDNFLeg2() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_2");
    }

    @Test
    @Disabled
    void massStartNoneDNFLeg3() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_3");
    }

    @Test
    @Disabled
    void massStartNoneDNFLeg4() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_4");
    }

    @Test
    @Disabled
    void massStartNoneDNFLeg3And4NotCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_3_4a");
    }

    @Test
    @Disabled
    void massStartNoneDNFLeg3And4ButCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_none/dnf_leg_3_4b");
    }

    @Test
    @Disabled
    void massStart34AllCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/all_completed");
    }

    @Test
    @Disabled
    void massStart34DNFLeg1() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_1");
    }

    @Test
    @Disabled
    void massStart34DNFLeg1And2And3() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_1_2_3");
    }

    @Test
    @Disabled
    void massStart34DNFButCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_1_2_3_4a");
    }

    @Test
    @Disabled
    void massStart34DNFNotCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_1_2_3_4b");
    }

    @Test
    @Disabled
    void massStart34DNFLeg2() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_2");
    }

    @Test
    @Disabled
    void massStart34DNFLeg3() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_3");
    }

    @Test
    @Disabled
    void massStart34DNFLeg3And4NoFinishes() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_3_4a");
    }

    @Test
    @Disabled
    void massStart34DNFLeg3And4ButCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_3_4b");
    }

    @Test
    @Disabled
    void massStart34DNFLeg4() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/dnf_leg_4");
    }

    @Test
    @Disabled
    void massStart34FirstLegFinishAfterMassStart3() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/first_leg_finish_after_mass_start_3");
    }

    @Test
    @Disabled
    void massStart34FirstLegFinishAfterMassStart4() throws Exception {
        testExpectedCompletion("relay_race/mass_start_3_4/first_leg_finish_after_mass_start_4");
    }

    @Test
    @Disabled
    void massStart4AllCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/all_completed");
    }

    @Test
    @Disabled
    void massStart4LegsSwapped() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/legs_swapped");
    }

    @Test
    @Disabled
    void massStart4DNFLeg1() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_1");
    }

    @Test
    @Disabled
    void massStart4DNFLeg1And2And3() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_1_2_3");
    }

    @Test
    @Disabled
    void massStart4DNFButCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_1_2_3_4a");
    }

    @Test
    @Disabled
    void massStart4DNFNotCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_1_2_3_4b");
    }

    @Test
    @Disabled
    void massStart4DNFLeg2() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_2");
    }

    @Test
    @Disabled
    void massStart4DNFLeg3() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_3");
    }

    @Test
    @Disabled
    void massStart4DNFLeg3And4NoFinishes() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_3_4a");
    }

    @Test
    @Disabled
    void massStart4DNFLeg3And4ButCompleted() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_3_4b");
    }

    @Test
    @Disabled
    void massStart4DNFLeg4() throws Exception {
        testExpectedCompletion("relay_race/mass_start_4/dnf_leg_4");
    }

    @Test
    @Disabled
    void individualRunnerStartTimeLeg1() throws Exception {
        testExpectedCompletion("relay_race/individual_runner_start_time/leg_1");
    }

    @Test
    @Disabled
    void individualRunnerStartTimeLeg3() throws Exception {
        testExpectedCompletion("relay_race/individual_runner_start_time/leg_3");
    }

    @Test
    @Disabled
    void alternativePrizeReportingOrder() throws Exception {
        testExpectedCompletion("relay_race/alternative_prize_reporting_order");
    }

    @Test
    void prizeCategoryGroups() throws Exception {
        testExpectedCompletion("relay_race/prize_category_groups");
    }

    @Test
    @Disabled
    void teamNameIncludesComma() throws Exception {
        testExpectedCompletion("relay_race/team_name_includes_comma");
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////

    @Test
    void illegalDNFTime() throws Exception {
        testExpectedErrorMessage("relay_race/illegal_dnf_time", () -> STR."invalid entry 'XXX' for key '\{KEY_DNF_FINISHERS}' in file '\{config_file_path.getFileName()}'");
    }

    @Test
    void illegalMassStartTime() throws Exception {
        testExpectedErrorMessage("relay_race/illegal_mass_start_time", () -> STR."invalid mass start time for key '\{KEY_MASS_START_ELAPSED_TIMES}' in file '\{config_file_path.getFileName()}'");
    }

    @Test
    void illegalMassStartTimeOrder() throws Exception {
        testExpectedErrorMessage("relay_race/illegal_mass_start_time_order", () -> STR."invalid mass start time order for key '\{KEY_MASS_START_ELAPSED_TIMES}' in file '\{config_file_path.getFileName()}'");
    }



    @Test
    void missingPropertyNumberOfLegs() throws Exception {
        testExpectedErrorMessage("relay_race/missing_property_number_of_legs", () -> STR."no entry for key '\{KEY_NUMBER_OF_LEGS}' in file '\{config_file_path.getFileName()}'");
    }

    @Test
    void missingPropertyPairedLegs() throws Exception {
        testExpectedErrorMessage("relay_race/missing_property_paired_legs", () -> STR."no entry for key '\{KEY_PAIRED_LEGS}' in file '\{config_file_path.getFileName()}'");
    }

    @Test
    void duplicateTeamNumber() throws Exception {
        testExpectedErrorMessage("relay_race/duplicate_team_number", () -> STR."duplicate bib number '3' in file '\{getFileNameForPathProperty(KEY_ENTRIES_PATH)}'");
    }

    @Test
    void duplicateTeamName() throws Exception {
        testExpectedErrorMessage("relay_race/duplicate_team_name", () -> STR."duplicate entry 'Team 2' in file '\{getFileNameForPathProperty(KEY_ENTRIES_PATH)}'");
    }

    @Test
    void illegalCategory() throws Exception {
        testExpectedErrorMessage("relay_race/illegal_category", () -> STR."invalid entry '3 Team 3 Men Senior Jackbruce Martin King & Leland Donaldson Neil MacDonald & Myles  Christie Hubert Gray' at line 3 in file '\{getFileNameForPathProperty(KEY_ENTRIES_PATH)}'");
    }

    @Test
    void illegalTeamComposition() throws Exception {
        testExpectedErrorMessage("relay_race/illegal_team_composition", () -> STR."invalid entry '3\tTeam 3\tOS\tJackbruce\tNeil MacDonald & Myles  Christie\tHubert Gray' at line 3 in file '\{getFileNameForPathProperty(KEY_ENTRIES_PATH)}'");
    }

    @Test
    @Disabled
    void extraResult() throws Exception {
        testExpectedErrorMessage("relay_race/extra_result", () -> STR."surplus result for team '2' in file '\{getFileNameForPathProperty(KEY_RAW_RESULTS_PATH)}'");
    }

    @Test
    @Disabled
    void unregisteredTeam() throws Exception {
        testExpectedErrorMessage("relay_race/unregistered_team", () -> STR."invalid bib number '4' in file '\{getFileNameForPathProperty(KEY_RAW_RESULTS_PATH)}'");
    }


    @Test
    @Disabled
    void illegalRawTime() throws Exception {
        testExpectedErrorMessage("relay_race/illegal_raw_time", () -> STR."invalid record '3\tXXX' at line 13 in file '\{getFileNameForPathProperty(KEY_RAW_RESULTS_PATH)}'");
    }

    @Test
    @Disabled
    void switchedResult() throws Exception {
        testExpectedErrorMessage("relay_race/switched_result", () -> STR."surplus result for team '2' in file '\{getFileNameForPathProperty(KEY_RAW_RESULTS_PATH)}'");
    }

    @Test
    @Disabled
    void resultsOutOfOrderA() throws Exception {
        testExpectedErrorMessage("relay_race/results_out_of_order_a", () -> STR."result out of order at line 15 in file '\{getFileNameForPathProperty(KEY_RAW_RESULTS_PATH)}'");
    }

    @Test
    @Disabled
    void resultsOutOfOrderB() throws Exception {
        testExpectedErrorMessage("relay_race/results_out_of_order_b", () -> STR."result out of order at line 16 in file '\{getFileNameForPathProperty(KEY_RAW_RESULTS_PATH)}'");
    }
}
