#!/bin/sh

# Add to .git/hooks/pre-commit in project directory.

if git diff --cached | grep -q '^USER_TEST_DIRECTORY_PATH ='; then
    echo "Commit blocked: debug mode is enabled."
    exit 1
fi

mvn license:check
if [ $? -ne 0 ]; then
    echo "Commit blocked: licence headers invalid."
    exit 1
fi
