#!/bin/sh

# Add to .git/hooks/pre-commit in project directory.

if grep -q '^ *USER_TEST_DIRECTORY_PATH =' "src/test/resources/test_config.txt"; then
    echo "Commit blocked: debug mode is enabled."
    exit 1
fi

mvn license:check
if [ $? -ne 0 ]; then
    echo "Commit blocked: licence headers invalid."
    exit 1
fi

mvn modernizer:modernizer
if [ $? -ne 0 ]; then
    echo "Commit blocked: obsolete API."
    exit 1
fi
