name: Maven Build and Test (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/maven-build-and-test.yml
    with:
      platform: macos-latest
