name: Maven Build and Test

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      upload-dependencies:
        required: false
        type: boolean
        default: false

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ inputs.platform }}

    steps:
    - name: Check out project
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B verify

    - name: Upload dependencies
      if: inputs.upload-dependencies
      uses: advanced-security/maven-dependency-submission-action@v4
