name: Maven Build and Test (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and test (macOS)
    runs-on: macos-latest
    permissions:
      # Need write permission since that's required for upload dependencies step, even though that step won't run.
      contents: write
    steps:
      - name: Check out project
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955                                        # v4.3.0

      - name: Build and test
        uses: ./.github/actions/build-and-test
